repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.0-beta.0
    hooks:
      - id: eslint
        name: ESLint Backend & Frontend
        entry: npx eslint .
        language: node
        files: ^app/(backend|frontend)/.*\.(js|ts|jsx)$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        name: Prettier Check
        entry: npx prettier --check .
        language: node
        files: ^app/.*\.(js|ts|jsx|json|css|md|yaml)$
