services:
  clb-back:
    image: clb-back:latest
    build:
      context: ../collegeLaBoussoleApp/backend
    container_name: clb-back
    restart: unless-stopped
    env_file:
      - ../collegeLaBoussoleApp/backend/.env
    ports:
      - "127.0.0.1:5000:5000"

  clb-front:
    image: clb-front:latest
    build:
      context: ../collegeLaBoussoleApp/frontend
    container_name: clb-front
    restart: unless-stopped
    environment:
      HOSTNAME: "0.0.0.0"
    ports:
      - "127.0.0.1:3007:3000"
