#!/bin/sh

BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "🔎 Vérification branche: $BRANCH"

case "$BRANCH" in
  feature/[0-9]*-*|feat/[0-9]*-*|fix/[0-9]*-*|hotfix/[0-9]*-*)
    echo "✅ Nom de branche valide"
    ;;
  *)
    echo "❌ Nom de branche invalide"
    echo "Format attendu:"
    echo "feature/123-description"
    echo "fix/123-description"
    echo "hotfix/123-description"
    exit 1
    ;;
esac