name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installer backend & frontend sans scripts
      - name: Backend tests
        run: |
          cd collegeLaBoussoleApp/backend
          npm install --ignore-scripts
          npm test

      - name: Frontend tests
        run: |
          cd collegeLaBoussoleApp/frontend
          npm install --ignore-scripts
          npm test
